env:
  DOCKERHUB_REPO: electricsql
  IMAGE_NAME: pglite-builder

agent:
  docker: true
  gcp: true

steps:
  - label: '🚀 Build & publish the builder image to Docker Hub'
    command:
      - source .buildconfig
      - export PGLITE_BUILDER_IMAGE_NAME="${DOCKERHUB_REPO}/${IMAGE_NAME}"
      - export BUILDER_VERSION="${PG_VERSION}_${SDK_VERSION}"
      - docker buildx build --platform linux/arm64/v8,linux/amd64 --push
        --build-arg PG_VERSION=$${PG_VERSION}
        --build-arg SDK_VERSION=$${SDK_VERSION}
        -t $${PGLITE_BUILDER_IMAGE_NAME}:$${BUILDER_VERSION}
        -t $${PGLITE_BUILDER_IMAGE_NAME}:latest
        .
