env:
  DOCKERHUB_REPO: electricsql
  IMAGE_NAME: pglite-builder

agent:
  docker: true
  gcp: true

steps:
  - label: '🚀 Build & publish the builder image to Docker Hub'
    command:
      - cat .buildconfig
      - echo "xargs" && export $(xargs < .buildconfig) && echo ${{PG_VERSION}}
      - echo "source" && source ./.buildconfig && echo ${{PG_VERSION}}
      - export IMGNAME="electricsql/pglite"
      - export IMGTAG="${PG_VERSION}_${SDK_VERSION}"
      - |
        if docker manifest inspect $${IMGNAME}:$${IMGTAG} >/dev/null 2>&1; then
          echo "Image $${IMGNAME}:$${IMGTAG} already exists on Docker Hub. Exiting successfully."
          exit 0
        fi
      # - docker buildx build --platform linux/arm64/v8,linux/amd64 --push
      #   --build-arg PG_VERSION=$${PG_VERSION}
      #   --build-arg SDK_VERSION=$${SDK_VERSION}
      #   -t $${IMGNAME}:$${IMGTAG}
      #   -t $${IMGNAME}:latest
      #   .
